### ISSUE TITLE
Complex Yaml reading in dockerflow.

### ISSUE THREAD

**Issue by vangalamaheshh** [googlegenomics/dockerflow#38]
Hello -

If I have a yaml file like this:

sample_names:
  sn1:
    left: /path/to/left_file
    right: /path/to/right_file
  sn2:
    left: /path/to/..
    right: /path/to/..
  

How can I access "sample_names"."sn1"."left" value in dockerflow?

Thanks much.

Regards,
Mahesh

**Comment by jbingham** [comment]
Where is this yaml? Is it in your settings file, or is it one of your input files?

**Comment by vangalamaheshh** [comment]
Hi @jbingham -

that would be workflow-args.yaml file.

- Mahesh

**Comment by jbingham** [comment]
I see. So the request is to support structured parameters rather than flat strings, as in the current workflow args.

Current way:
 
inputs:
  samples: |
    sn1
    sn2
  left: |
    /path/to/sn1_left
    /path/to/sn2_left
  right: |
    /path/to/sn1_right
    /path/to/sn2_right

In your Docker command, you'd get env variables ${left_1}, ${left_2}.

That should work -- provided that you know upfront how many samples there are. Do you?

**Comment by vangalamaheshh** [comment]
@jbingham 👍 I think this should satisfy my use case. Thank you.

Regards,
Mahesh

**Comment by jbingham** [comment]
Great! Reopen or file again if it doesn't work for you.
