### ISSUE TITLE
Scalability questions

### ISSUE THREAD

**Issue by vardaofthevalier** [googlegenomics/dockerflow#7]
I have two questions relating to scaling pipelines using Dockerflow:

1) I notice that the Dockerflow task runner process polls for completion status of the GGP job that it monitors.  One issue that I've run into in the past while developing code to monitor the pipeline jobs is that having too many concurrent processes querying the operations (even if they occasionally sleep) can cause frequent QPS errors which leads to stalled reporting of jobs.  Do you foresee this being an issue here as well, or is there other code somewhere else that handles orchestrating the polling threads and/or the QPS errors?

2) How many concurrent processes can the Dataflow head node for the workflow handle at once?  I'm just wondering what would happen if I wanted to run an embarrassingly parallel  scatter step (such as running FastQC on potentially tens of thousands of input files) would the Dataflow node be able to handle that without any trouble?  Mainly I think this is important when designing the topology of the graph, so any recommendations you have about the best way to split up the work would be useful.

**Comment by jbingham** [comment]
Great questions. No definitive answers here, but some guesses:

1) I think I've seen transient errors like that. Dataflow has some retries built in, and Dockerflow has some more. I've seen Dataflow catch server errors on trying to reach the API, and get past them on retry. I'd be interested to hear if you do encounter issues.

2) I have no idea :) To the user of Dataflow, it looks headless. There are only workers. The workers don't do much work, since they just farm out to the Pipelines API. I don't see why a scatter on ten thousand input files shouldn't work. But I definitely haven't tried. 

if  the Dataflow nodes do get overwhelmed, you can switch to a bigger VM instance type using the flag --machine-type. Then provide any of the GCE instance types.

**Comment by pgrosu** [comment]
@jbingham Is this the same Dataflow that has the following 4000 core maximum, or is it possible to have 10,000 or more workers?

https://cloud.google.com/dataflow/service/dataflow-service-desc#workers

Thanks,
~p

**Comment by jbingham** [comment]
Dataflow is only used for orchestration, so there's typically just one
Dataflow node that counts toward that quota. The Pipelines API calls all
get queued up and run outside of Dataflow's quotas. The Dataflow node is
technically a worker node, not a head node, from the perspective of
Dataflow. From the perspective of Dockerflow, though, yes, it's a head node
and a single point of failure.

**Comment by pgrosu** [comment]
But can it utilize the following `automatic restart`  setting to always stay up?

https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#autorestart

**Comment by jbingham** [comment]
Dataflow might use that setting -- or it might just start a new VM, since
transforms are meant to be idempotent and stateless. Dockerflow is not
really using Dataflow in the intended way :-)

**Comment by pgrosu** [comment]
No problemo, still very useful with many opportunities for possibilities :)
